#!/bin/bash
# .env Loader Script for easy reference
# This shows what your .env file contains

echo "=========================================="
echo "Current .env Configuration"
echo "=========================================="
echo ""
echo "Environment Mode:"
echo "  ENVIRONMENT=development"
echo ""
echo "Database:"
echo "  Using SQLite locally (students.db)"
echo "  Will use PostgreSQL on Render"
echo ""
echo "Security Keys:"
echo "  SECRET_KEY=(set in .env)"
echo "  JWT_SECRET=(set in .env)"
echo ""
echo "Email Configuration (Mock on localhost):"
echo "  MAIL_SERVER=smtp.gmail.com"
echo "  MAIL_PORT=587"
echo "  MAIL_USE_TLS=True"
echo "  MAIL_USERNAME=(optional)"
echo "  MAIL_PASSWORD=(optional)"
echo "  MAIL_DEFAULT_SENDER=noreply@tii.com"
echo "  ADMIN_EMAIL=codestiiwebadmin@gmail.com"
echo ""
echo "=========================================="
echo "To see actual values: cat .env"
echo "=========================================="
